//while-loop 範例練習_3
public class Practice_10 {

	public static void main(String[] args) {
		// TODO Autogenerated method stub
		int all = 5000000 ;
		double now = all * 0.75;
		double w = 20000;
		int h = 0 ;
		
			while(w + now < all){
				w = w + w * 0.15;
				h++;
			}
		System.out.print("再  " +h+ " 小時之後，水庫就會到達滿水位。");

	}

}
